"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""

from typing import TYPE_CHECKING

import numpy as np
from magicgui import magic_factory
from magicgui.widgets import CheckBox, ComboBox, Container, create_widget, PushButton
from qtpy.QtWidgets import QHBoxLayout, QPushButton, QWidget, QVBoxLayout


from scipy import ndimage
from skimage.transform import resize
from skimage.util import img_as_float

if TYPE_CHECKING:
    import napari


# Uses the `autogenerate: true` flag in the plugin manifest
# to indicate it should be wrapped as a magicgui to autogenerate
# a widget.
def threshold_autogenerate_widget(
    img: "napari.types.ImageData",
    threshold: "float",
) -> "napari.types.LabelsData":
    return img_as_float(img) > threshold


# the magic_factory decorator lets us customize aspects of our widget
# we specify a widget type for the threshold parameter
# and use auto_call=True so the function is called whenever
# the value of a parameter changes
@magic_factory(
    threshold={"widget_type": "FloatSlider", "max": 1}, auto_call=True
)
def threshold_magic_widget(
    img_layer: "napari.layers.Image", threshold: "float"
) -> "napari.types.LabelsData":
    return img_as_float(img_layer.data) > threshold


# if we want even more control over our widget, we can use
# magicgui `Container`
class ImageThreshold(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer
        # use create_widget to generate widgets from type annotations
        self._image_layer_combo = create_widget(
            label="Image", annotation="napari.layers.Image"
        )
        self._threshold_slider = create_widget(
            label="Threshold", annotation=float, widget_type="FloatSlider"
        )
        self._threshold_slider.min = 0
        self._threshold_slider.max = 1
        # use magicgui widgets directly
        self._invert_checkbox = CheckBox(text="Keep pixels below threshold")

        # connect your own callbacks
        self._threshold_slider.changed.connect(self._threshold_im)
        self._invert_checkbox.changed.connect(self._threshold_im)

        # append into/extend the container with your widgets
        self.extend(
            [
                self._image_layer_combo,
                self._threshold_slider,
                self._invert_checkbox,
            ]
        )

    def _threshold_im(self):
        image_layer = self._image_layer_combo.value
        if image_layer is None:
            return

        image = img_as_float(image_layer.data)
        name = image_layer.name + "_thresholded"
        threshold = self._threshold_slider.value
        if self._invert_checkbox.value:
            thresholded = image < threshold
        else:
            thresholded = image > threshold
        if name in self._viewer.layers:
            self._viewer.layers[name].data = thresholded
        else:
            self._viewer.add_labels(thresholded, name=name)



class ImageResize(Container):
    """Container widget for resizing images with different interpolation algorithms."""

    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer

        # Image selection
        self._image_layer_combo = create_widget(
            label="Image", annotation="napari.layers.Image"
        )

        # Output size widgets
        self._width_spinbox = create_widget(
            label="Width", annotation=int, widget_type="SpinBox"
        )
        self._width_spinbox.min = 1
        self._width_spinbox.max = 10000
        self._width_spinbox.value = 512

        self._height_spinbox = create_widget(
            label="Height", annotation=int, widget_type="SpinBox"
        )
        self._height_spinbox.min = 1
        self._height_spinbox.max = 10000
        self._height_spinbox.value = 512

        # Scale factor widgets
        self._scale_x_spinbox = create_widget(
            label="Scale X", annotation=float, widget_type="FloatSpinBox"
        )
        self._scale_x_spinbox.min = 0.01
        self._scale_x_spinbox.max = 100.0
        self._scale_x_spinbox.value = 1.0
        self._scale_x_spinbox.step = 0.1

        self._scale_y_spinbox = create_widget(
            label="Scale Y", annotation=float, widget_type="FloatSpinBox"
        )
        self._scale_y_spinbox.min = 0.01
        self._scale_y_spinbox.max = 100.0
        self._scale_y_spinbox.value = 1.0
        self._scale_y_spinbox.step = 0.1

        # Resize mode selection
        self._mode_combo = ComboBox(
            label="Resize Mode",
            choices=["Absolute Size", "Scale Factor"],
            value="Absolute Size",
        )

        # Interpolation algorithm selection
        self._algorithm_combo = ComboBox(
            label="Algorithm",
            choices=[
                "Nearest Neighbor",
                "Bilinear",
                "Bicubic",
                "Lanczos",
            ],
            value="Bilinear",
        )

        # Maintain aspect ratio checkbox
        self._maintain_aspect_checkbox = CheckBox(text="Maintain Aspect Ratio")

        # Apply button
        self._apply_button = PushButton(text="Apply Resize!")
        self._apply_button.clicked.connect(self._resize_image)

        # Add all widgets to container
        self.extend(
            [
                self._image_layer_combo,
                self._mode_combo,
                self._width_spinbox,
                self._height_spinbox,
                self._scale_x_spinbox,
                self._scale_y_spinbox,
                self._maintain_aspect_checkbox,
                self._algorithm_combo,
                self._apply_button,
            ]
        )

        # Connect callbacks
        self._image_layer_combo.changed.connect(self._on_image_changed)
        self._mode_combo.changed.connect(self._on_mode_changed)
        self._width_spinbox.changed.connect(self._on_size_changed)
        self._height_spinbox.changed.connect(self._on_size_changed)

        # Initialize visibility
        self._on_mode_changed()

    # -------------------
    # Callback methods
    # -------------------
    def _on_image_changed(self):
        """Update size spinboxes when image is selected."""
        image_layer = self._image_layer_combo.value
        if image_layer is not None and hasattr(image_layer, "data"):
            shape = image_layer.data.shape
            if len(shape) >= 2:
                self._height_spinbox.value = shape[-2]
                self._width_spinbox.value = shape[-1]

    def _on_mode_changed(self):
        """Toggle visibility of size/scale widgets based on mode."""
        mode = self._mode_combo.value
        if mode == "Absolute Size":
            self._width_spinbox.show()
            self._height_spinbox.show()
            self._scale_x_spinbox.hide()
            self._scale_y_spinbox.hide()
        else:  # Scale Factor
            self._width_spinbox.hide()
            self._height_spinbox.hide()
            self._scale_x_spinbox.show()
            self._scale_y_spinbox.show()

    def _on_size_changed(self):
        """Maintain aspect ratio in absolute size mode."""
        if not self._maintain_aspect_checkbox.value:
            return

        image_layer = self._image_layer_combo.value
        if image_layer is None or not hasattr(image_layer, "data"):
            return

        shape = image_layer.data.shape
        if len(shape) < 2:
            return

        original_height, original_width = shape[-2], shape[-1]
        aspect_ratio = original_width / original_height

        sender = self.sender()
        if sender == self._width_spinbox:
            new_width = self._width_spinbox.value
            new_height = int(new_width / aspect_ratio)
            self._height_spinbox.value = new_height
        elif sender == self._height_spinbox:
            new_height = self._height_spinbox.value
            new_width = int(new_height * aspect_ratio)
            self._width_spinbox.value = new_width

    # -------------------
    # Resize operation
    # -------------------
    def _resize_image(self):
        image_layer = self._image_layer_combo.value
        if image_layer is None:
            return

        image = image_layer.data
        mode = self._mode_combo.value
        algorithm = self._algorithm_combo.value

        # Determine output shape
        if mode == "Absolute Size":
            output_height = self._height_spinbox.value
            output_width = self._width_spinbox.value
        else:  # Scale Factor
            scale_y = self._scale_y_spinbox.value
            scale_x = self._scale_x_spinbox.value
            original_shape = image.shape
            output_height = int(original_shape[-2] * scale_y)
            output_width = int(original_shape[-1] * scale_x)

        # Map algorithm names
        algorithm_map = {"Nearest Neighbor": 0, "Bilinear": 1, "Bicubic": 3, "Lanczos": None}

        try:
            # Determine output shape for different dimensions
            if len(image.shape) == 2:
                output_shape = (output_height, output_width)
            elif len(image.shape) == 3:
                if image.shape[-1] in [3, 4]:  # RGB / RGBA
                    output_shape = (output_height, output_width, image.shape[-1])
                else:  # 3D grayscale
                    output_shape = (
                        int(image.shape[0] * (output_height / image.shape[-2])),
                        output_height,
                        output_width,
                    )
            else:
                scale_factors = [1.0] * len(image.shape)
                scale_factors[-2] = output_height / image.shape[-2]
                scale_factors[-1] = output_width / image.shape[-1]
                output_shape = tuple(
                    int(s * f) for s, f in zip(image.shape, scale_factors)
                )

            # Perform resize
            if algorithm == "Lanczos":
                resized = resize(
                    image, output_shape, order=3, mode="reflect", anti_aliasing=True
                )
            else:
                order = algorithm_map[algorithm]
                if len(image.shape) == 2:
                    resized = ndimage.zoom(
                        image,
                        (output_height / image.shape[0], output_width / image.shape[1]),
                        order=order,
                    )
                elif len(image.shape) == 3 and image.shape[-1] in [3, 4]:
                    resized = np.zeros(output_shape, dtype=image.dtype)
                    for i in range(image.shape[-1]):
                        resized[..., i] = ndimage.zoom(
                            image[..., i],
                            (
                                output_height / image.shape[0],
                                output_width / image.shape[1],
                            ),
                            order=order,
                        )
                else:
                    zoom_factors = [
                        out_s / in_s for out_s, in_s in zip(output_shape, image.shape)
                    ]
                    resized = ndimage.zoom(image, zoom_factors, order=order)

            # Add resized image as new layer
            name = image_layer.name + "_resized"
            if name in self._viewer.layers:
                self._viewer.layers[name].data = resized
            else:
                self._viewer.add_image(resized, name=name)

        except Exception as e:
            print(f"Error resizing image: {e}")

class ExampleQWidget(QWidget):
    # your QWidget.__init__ can optionally request the napari viewer instance
    # use a type annotation of 'napari.viewer.Viewer' for any parameter
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self.viewer = viewer

        btn = QPushButton("Click me!")
        btn.clicked.connect(self._on_click)

        self.setLayout(QHBoxLayout())
        self.layout().addWidget(btn)

    def _on_click(self):
        print("napari has", len(self.viewer.layers), "layers")
