"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""

import ast
import base64
import json
import os
import os.path as osp

import imgviz
import matplotlib.pyplot as plt
import napari
import numpy as np
import pandas as pd
import torch
from labelme import utils, utils as labelme_utils
from magicgui.widgets import (
    CheckBox,
    ComboBox,
    Container,
    FileEdit,
    FloatSpinBox,
    Label,
    PushButton,
    SpinBox,
    Table,
    TextEdit,
    create_widget,
)
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from napari.layers import Image, Image as ImageLayer, Labels
from napari.qt.threading import thread_worker
from PIL import Image as PILImage
from qtpy.QtWidgets import QFileDialog, QSizePolicy, QWidget, QVBoxLayout

from emcfsys.PhenotypeAnalysis.functions import analyze_phenotypes

from .utils.image_resize_ops import resize_array, spatial_shape, target_size_from_mode
from .utils.inference_tasks import (
    SegmentationInferenceRequest,
    SlidingWindowInferenceRequest,
    run_full_inference_task,
    run_sliding_inference_task,
)
from .utils.emcellfiner_tasks import (
    EMCellFinerRequest,
    iter_emcellfiner_batch_inference,
    resolve_emcellfiner_device,
    run_emcellfiner_single_inference,
)
from .utils.io_utils import collect_image_files, ensure_directory, normalize_optional_path
from .utils.training_tasks import SegmentationTrainingRequest, run_training_task
from .utils.viewer_ops import upsert_image_layer, upsert_labels_layer

# the magic_factory decorator lets us customize aspects of our widget
# we specify a widget type for the threshold parameter
# and use auto_call=True so the function is called whenever
# the value of a parameter changes
backbone_zoom = [   "emcellfound_vit_base",
                 
                    "resnet34", "resnet50", "resnet101", 
                
                    "convnext_tiny", "convnext_small", "convnext_base", "convnext_large",
                    
                    "efficientnet_b0", "efficientnet_b2", 
                    "efficientnet_b4" , "efficientnet_b6", 
                    "efficientnet_b7",
                    
                    "efficientnetv2_s", "efficientnetv2_m", "efficientnetv2_l",
                    
                    "rexnetr_200.sw_in12k", "rexnetr_300.sw_in12k", 
                    
                    "vit_base_patch32_clip_448.laion2b_ft_in12k_in1k", 
                    "vit_so400m_patch14_siglip_gap_448.pali_refcoco_seg",
                    
                    "vit_small_patch16_dinov3.lvd1689m", "vit_base_patch16_dinov3.lvd1689m",
                    "vit_large_patch16_dinov3.lvd1689m", "vit_huge_patch16_dinov3.lvd1689m"]


model_zoom = ["deeplabv3plus", "unet", "pspnet", "upernet", "orgsegnetv2"]


def _configure_wrapped_label(widget: Label):
    native = widget.native
    native.setWordWrap(True)
    native.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)


def _configure_wrapped_labels(*widgets: Label):
    for widget in widgets:
        _configure_wrapped_label(widget)

class ImageResize(Container):
    """Container widget for resizing images with different interpolation algorithms."""

    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer

        # Image selection
        self._image_layer_combo = create_widget(
            label="Image", annotation="napari.layers.Image"
        )

        # Output size widgets
        self._width_spinbox = create_widget(
            label="Width", annotation=int, widget_type="SpinBox"
        )
        self._width_spinbox.min = 1
        self._width_spinbox.max = 10000
        self._width_spinbox.value = 512

        self._height_spinbox = create_widget(
            label="Height", annotation=int, widget_type="SpinBox"
        )
        self._height_spinbox.min = 1
        self._height_spinbox.max = 10000
        self._height_spinbox.value = 512

        # Scale factor widgets
        self._scale_x_spinbox = create_widget(
            label="Scale X", annotation=float, widget_type="FloatSpinBox"
        )
        self._scale_x_spinbox.min = 0.01
        self._scale_x_spinbox.max = 100.0
        self._scale_x_spinbox.value = 1.0
        self._scale_x_spinbox.step = 0.1

        self._scale_y_spinbox = create_widget(
            label="Scale Y", annotation=float, widget_type="FloatSpinBox"
        )
        self._scale_y_spinbox.min = 0.01
        self._scale_y_spinbox.max = 100.0
        self._scale_y_spinbox.value = 1.0
        self._scale_y_spinbox.step = 0.1

        # Resize mode selection
        self._mode_combo = ComboBox(
            label="Resize Mode",
            choices=["Absolute Size", "Scale Factor"],
            value="Absolute Size",
        )

        # Interpolation algorithm selection
        self._algorithm_combo = ComboBox(
            label="Algorithm",
            choices=[
                "Nearest Neighbor",
                "Bilinear",
                "Bicubic",
                "Lanczos",
            ],
            value="Bilinear",
        )

        # Maintain aspect ratio checkbox
        self._maintain_aspect_checkbox = CheckBox(text="Maintain Aspect Ratio")

        # Apply button
        self._apply_button = PushButton(text="Apply Resize!")
        self._apply_button.clicked.connect(self._resize_image)

        # Add all widgets to container
        self.extend(
            [
                self._image_layer_combo,
                self._mode_combo,
                self._width_spinbox,
                self._height_spinbox,
                self._scale_x_spinbox,
                self._scale_y_spinbox,
                self._maintain_aspect_checkbox,
                self._algorithm_combo,
                self._apply_button,
            ]
        )

        # Connect callbacks
        self._image_layer_combo.changed.connect(self._on_image_changed)
        self._mode_combo.changed.connect(self._on_mode_changed)
        self._width_spinbox.changed.connect(self._on_size_changed)
        self._height_spinbox.changed.connect(self._on_size_changed)

        # Initialize visibility
        self._on_mode_changed()

    def _selected_image_layer(self):
        return self._image_layer_combo.value

    def _selected_image_data(self):
        image_layer = self._selected_image_layer()
        if image_layer is None or not hasattr(image_layer, "data"):
            return None
        return image_layer.data

    def _selected_spatial_shape(self):
        image = self._selected_image_data()
        return spatial_shape(image)

    def _set_resize_mode_visibility(self, absolute_size_mode):
        self._width_spinbox.visible = absolute_size_mode
        self._height_spinbox.visible = absolute_size_mode
        self._scale_x_spinbox.visible = not absolute_size_mode
        self._scale_y_spinbox.visible = not absolute_size_mode

    def _target_size_from_mode(self, image):
        return target_size_from_mode(
            image=image,
            mode=self._mode_combo.value,
            width=self._width_spinbox.value,
            height=self._height_spinbox.value,
            scale_x=self._scale_x_spinbox.value,
            scale_y=self._scale_y_spinbox.value,
        )

    # -------------------
    # Callback methods
    # -------------------
    def _on_image_changed(self):
        """Update size spinboxes when image is selected."""
        spatial_shape = self._selected_spatial_shape()
        if spatial_shape is None:
            return
        self._height_spinbox.value, self._width_spinbox.value = spatial_shape

    def _on_mode_changed(self):
        """Toggle visibility of size/scale widgets based on mode."""
        self._set_resize_mode_visibility(self._mode_combo.value == "Absolute Size")

    def _on_size_changed(self):
        """Maintain aspect ratio in absolute size mode."""
        if not self._maintain_aspect_checkbox.value:
            return

        spatial_shape = self._selected_spatial_shape()
        if spatial_shape is None:
            return

        original_height, original_width = spatial_shape
        aspect_ratio = original_width / original_height

        sender = self.sender()
        if sender == self._width_spinbox:
            new_width = self._width_spinbox.value
            new_height = int(new_width / aspect_ratio)
            self._height_spinbox.value = new_height
        elif sender == self._height_spinbox:
            new_height = self._height_spinbox.value
            new_width = int(new_height * aspect_ratio)
            self._width_spinbox.value = new_width

    # -------------------
    # Resize operation
    # -------------------
    def _resize_image(self):
        image_layer = self._selected_image_layer()
        if image_layer is None:
            return

        image = image_layer.data
        output_height, output_width = self._target_size_from_mode(image)

        try:
            resized = resize_array(
                image,
                output_height,
                output_width,
                self._algorithm_combo.value,
            )
            upsert_image_layer(self._viewer, resized, image_layer.name + "_resized")
        except Exception as e:
            print(f"Error resizing image: {e}")

# -----------------------------
# DL Inference Container
# -----------------------------
class DLInferenceContainer(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer

        self.model_path = FileEdit(label="Model (.pt/.pth/.ptscript)")
        self._image_layer_combo = create_widget(label="Image", annotation="napari.layers.Image")
        self.num_classes = SpinBox(label="num classes", min=2, max=1000, step=1, value=2)
        self.device = ComboBox(label="Device", choices=["auto", "cpu", "cuda"], value="auto")
        self.backbone_name = ComboBox(label="Backbone", choices=backbone_zoom, value="emcellfound_vit_base")
        self.model_name = ComboBox(label="Model", choices=model_zoom, value="deeplabv3plus")
        self.img_size = SpinBox(label="Image size to model", min=1, max=4096, step=1, value=512)
        self.slide_window_size = SpinBox(label="Slide window size", min=1, max=4096, step=1, value=512)

        self.line_break = Label(value="-- OR inference in a image folder ---")
        self.inference_from_folder_mode = CheckBox(label="Inference from folder", value=False)
        self.image_folder = FileEdit(label="Image folder", nullable=True, mode="d")
        self.output_folder = FileEdit(label="Label mask output folder", nullable=True, mode="w")
        self.save_visualization = CheckBox(label="Save visualization mask", value=True)
        self.visualization_output_folder = FileEdit(label="Visualization output folder", nullable=True, mode="w")
        self.save_stacked_visualization = CheckBox(label="Save stacked image + visualization", value=False)
        self.stacked_visualization_output_folder = FileEdit(label="Stacked visualization output folder", nullable=True, mode="w")

        self.line_break2 = Label(value="--- Click to Full/Slide inference ---")
        _configure_wrapped_labels(self.line_break, self.line_break2)
        self._run_button_full = PushButton(text="Run Full Inference")
        self._run_button_slide = PushButton(text="Run Slide Inference")
        self._stop_button = PushButton(text="Stop Inference")

        self.extend([
            self.model_path,
            self._image_layer_combo,
            self.backbone_name,
            self.model_name,
            self.num_classes,
            self.device,
            self.img_size,
            self.slide_window_size,
            self.line_break,
            self.inference_from_folder_mode,
            self.image_folder,
            self.output_folder,
            self.save_visualization,
            self.visualization_output_folder,
            self.save_stacked_visualization,
            self.stacked_visualization_output_folder,
            self.line_break2,
            self._run_button_full,
            self._run_button_slide,
            self._stop_button,
        ])

        self._run_button_full.clicked.connect(self._run_inference_full)
        self._run_button_slide.clicked.connect(self._run_inference_slide)
        self._stop_button.clicked.connect(self._stop_worker)
        self.inference_from_folder_mode.changed.connect(self._update_folder_inference_state)
        self.save_visualization.changed.connect(self._update_visualization_output_state)
        self.save_stacked_visualization.changed.connect(self._update_stacked_visualization_output_state)

        self._worker = None
        self._stop_flag = False
        self._update_folder_inference_state()
        self._update_visualization_output_state()
        self._update_stacked_visualization_output_state()

    def _resolve_device(self):
        device = self.device.value
        return torch.device(device) if device != "auto" else None

    def _stop_checker(self):
        if self._stop_flag:
            print("[Frontend Checker] Stop flag detected.")
            return True
        return False

    def _prepare_run(self):
        self._stop_flag = False
        print("--- Starting new task, flag reset to False ---")

    def _update_folder_inference_state(self):
        folder_mode = self.inference_from_folder_mode.value
        self.image_folder.visible = folder_mode
        self.output_folder.visible = folder_mode
        self.save_visualization.visible = folder_mode
        self.save_stacked_visualization.visible = folder_mode
        self._update_visualization_output_state()
        self._update_stacked_visualization_output_state()

    def _update_visualization_output_state(self):
        self.visualization_output_folder.visible = (
            self.inference_from_folder_mode.value and self.save_visualization.value
        )

    def _update_stacked_visualization_output_state(self):
        self.stacked_visualization_output_folder.visible = (
            self.inference_from_folder_mode.value and self.save_stacked_visualization.value
        )

    def _build_full_inference_request(self, image_data, device, model_path, stop_checker):
        image_folder = normalize_optional_path(self.image_folder.value)
        label_output_folder = normalize_optional_path(self.output_folder.value)
        visualization_output_folder = normalize_optional_path(self.visualization_output_folder.value)
        stacked_visualization_output_folder = normalize_optional_path(self.stacked_visualization_output_folder.value)
        return SegmentationInferenceRequest(
            model_name=self.model_name.value,
            backbone_name=self.backbone_name.value,
            img_size=self.img_size.value,
            num_classes=self.num_classes.value,
            model_path=model_path,
            device=device,
            image=image_data,
            image_folder=image_folder if self.inference_from_folder_mode.value else None,
            label_output_folder=label_output_folder,
            visualization_output_folder=visualization_output_folder if self.save_visualization.value else None,
            save_visualization=self.save_visualization.value,
            stacked_visualization_output_folder=stacked_visualization_output_folder if self.save_stacked_visualization.value else None,
            save_stacked_visualization=self.save_stacked_visualization.value,
            stop_checker=stop_checker,
        )

    def _build_sliding_inference_request(self, image_data, device, model_path, stop_checker):
        image_folder = normalize_optional_path(self.image_folder.value)
        label_output_folder = normalize_optional_path(self.output_folder.value)
        visualization_output_folder = normalize_optional_path(self.visualization_output_folder.value)
        stacked_visualization_output_folder = normalize_optional_path(self.stacked_visualization_output_folder.value)
        return SlidingWindowInferenceRequest(
            model_name=self.model_name.value,
            backbone_name=self.backbone_name.value,
            img_size=self.img_size.value,
            num_classes=self.num_classes.value,
            model_path=model_path,
            device=device,
            image=image_data,
            image_folder=image_folder if self.inference_from_folder_mode.value else None,
            label_output_folder=label_output_folder,
            visualization_output_folder=visualization_output_folder if self.save_visualization.value else None,
            save_visualization=self.save_visualization.value,
            stacked_visualization_output_folder=stacked_visualization_output_folder if self.save_stacked_visualization.value else None,
            save_stacked_visualization=self.save_stacked_visualization.value,
            stop_checker=stop_checker,
            window_size=self.slide_window_size.value,
        )

    def _start_inference_worker(self, request_builder, task_runner, suffix):
        self._prepare_run()
        img_layer = self._image_layer_combo.value
        image_data = None if img_layer is None else img_layer.data
        request = request_builder(
            image_data,
            self._resolve_device(),
            normalize_optional_path(self.model_path.value),
            self._stop_checker,
        )

        @thread_worker
        def _worker():
            return task_runner(request)

        self._worker = _worker()

        def on_result(mask: np.ndarray):
            if img_layer is None or mask is None:
                return
            upsert_labels_layer(self._viewer, mask, f"{img_layer.name}{suffix}")

        self._worker.returned.connect(on_result)
        self._worker.start()

    def _run_inference_full(self):
        self._start_inference_worker(
            self._build_full_inference_request,
            run_full_inference_task,
            "_dl_mask",
        )

    def _run_inference_slide(self):
        self._start_inference_worker(
            self._build_sliding_inference_request,
            run_sliding_inference_task,
            "_slide_mask",
        )

    def _stop_worker(self):
        if self._worker is not None:
            print("Attempting to stop inference...")
            self._stop_flag = True
            self._worker.quit()
        else:
            print("No active inference worker to stop.")


class DLTrainingContainer(Container):

    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self._viewer = viewer
        self._stop_flag = False

        self.images_dir = FileEdit(label="Images folder", mode="d")
        self.masks_dir = FileEdit(label="Masks folder", mode="d")
        self.save_path = FileEdit(label="Save model as (.pth)", mode="d")
        self.pretrained_model = FileEdit(label="Pretrained model (.pth)", nullable=True, mode="r")

        self.backbone_name = ComboBox(label="Backbone", choices=backbone_zoom, value="resnet34")
        self.model_name = ComboBox(label="Model", choices=model_zoom, value="deeplabv3plus")

        self.lr = FloatSpinBox(label="Learning rate", min=1e-8, max=1.0, step=1e-4, value=1e-4)
        self.batch_size = SpinBox(label="Batch size", min=1, max=512, step=1, value=8)
        self.epochs = SpinBox(label="Epochs", min=1, max=1000, step=10, value=100)
        self.device = ComboBox(label="Device", choices=["auto", "cpu", "cuda"], value="auto")

        self.classes_num = SpinBox(label="Classes num", min=2, max=1000, step=1, value=2)
        self.target_size = SpinBox(label="Target size", min=1, max=10**8, value=512)
        self.ignore_index = SpinBox(label="Ignore the index in mask", min=-1, max=10**8, value=-1)

        self._train_button = PushButton(text="Start Training")
        self._stop_button = PushButton(text="Stop Training")
        self._log_label = Label(value="Training log:")
        _configure_wrapped_label(self._log_label)
        self._log_widget = TextEdit()
        self._log_widget.read_only = True
        self._log_widget.native.setMinimumHeight(180)

        self.extend([
            self.images_dir,
            self.masks_dir,
            self.save_path,
            self.pretrained_model,
            self.backbone_name,
            self.model_name,
            self.lr,
            self.batch_size,
            self.epochs,
            self.device,
            self.classes_num,
            self.target_size,
            self.ignore_index,
            self._train_button,
            self._stop_button,
            self._log_label,
            self._log_widget,
        ])

        self._train_button.clicked.connect(self._start_training)
        self._stop_button.clicked.connect(self._stop_training)

        self._fig, self._ax = plt.subplots()
        self._canvas = FigureCanvas(self._fig)
        self._x_values = []
        self._y_values = []

        self._canvas_widget = QWidget()
        v_layout = QVBoxLayout()
        v_layout.addWidget(self._canvas)
        self._canvas_widget.setLayout(v_layout)
        if self._viewer is not None:
            self._viewer.window.add_dock_widget(self._canvas_widget, name="Loss Curve", area="right")

        self._reset_training_plot()

    def _log(self, message):
        try:
            self._log_widget.append(message)
        except Exception:
            print(message)

    def _render_training_plot(self):
        self._ax.clear()
        self._ax.set_xlabel("Epoch")
        self._ax.set_ylabel("Loss")
        self._ax.set_title("Training Loss Curve")
        self._ax.plot(self._x_values, self._y_values, color="blue")
        self._fig.tight_layout()
        self._canvas.draw_idle()

    def _update_loss_curve(self, loss, epoch=None):
        if epoch is not None:
            self._x_values.append(epoch)
            self._y_values.append(loss)
        self._render_training_plot()

    def _reset_training_plot(self):
        self._x_values = []
        self._y_values = []
        self._render_training_plot()

    def _resolve_training_device(self):
        device = self.device.value
        if device != "auto":
            return torch.device(device)
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")

    def _build_training_request(self):
        return SegmentationTrainingRequest(
            images_dir=self.images_dir.value,
            masks_dir=self.masks_dir.value,
            save_path=self.save_path.value,
            backbone_name=self.backbone_name.value,
            model_name=self.model_name.value,
            lr=self.lr.value,
            batch_size=self.batch_size.value,
            epochs=self.epochs.value,
            device=self._resolve_training_device(),
            classes_num=self.classes_num.value,
            target_size=self.target_size.value,
            ignore_index=self.ignore_index.value,
            pretrained_model=normalize_optional_path(self.pretrained_model.value),
        )

    def _create_training_worker(self, request):
        @thread_worker
        def _worker():
            return run_training_task(
                request,
                update_loss_curve=self._update_loss_curve,
                log=self._log,
                stop_flag_fn=lambda: self._stop_flag,
            )

        return _worker()

    def _on_training_returned(self, logs, request):
        for epoch, batch, n_batches, loss, finished, epoch_time, metrics_info in logs:
            if batch == 0:
                if epoch_time is not None:
                    self._log(
                        f"Epoch {epoch} finished, avg loss {loss:.4f}, time {epoch_time:.2f}s, metric {metrics_info}"
                    )
                else:
                    self._log(f"Epoch {epoch} finished, avg loss {loss:.4f}")
            else:
                self._log(f"Epoch {epoch} batch {batch}/{n_batches} loss {loss:.4f}")
        if not self._stop_flag:
            self._log(f"Training finished. Model saved to: {request.save_path}")

    def _start_training(self):
        if self._viewer is None:
            return

        self._stop_flag = False
        self._reset_training_plot()
        request = self._build_training_request()
        worker = self._create_training_worker(request)
        worker.returned.connect(lambda logs: self._on_training_returned(logs, request))
        worker.start()

    def _stop_training(self):
        self._stop_flag = True
        self._log("Stop button clicked. Stopping training...")


#------------EMCellFiner=------
#------------EMCellFiner=------
class EMCellFinerSingleInferWidget(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self.viewer = viewer

        MODEL_ZOO = ["EMCellFiner"]

        self.model_path = FileEdit(label="Model (.pth)", nullable=True, mode="r")
        self._image_layer_combo = create_widget(
            label="Image",
            annotation=ImageLayer
        )

        self.device = ComboBox(label="Device", choices=["auto", "cpu", "cuda"], value="auto")
        self.scale = ComboBox(label="Scale", choices=[1, 2, 4], value=4)
        self.tile_size = ComboBox(label="Tile Size", choices=[256, 384, 512, 640], value=512)
        self.model_choice = ComboBox(label="Model", choices=MODEL_ZOO, value="EMCellFiner")
        self.label_model = Label(value="(If left blank, the model will be automatically downloaded from the cloud. Manual loading is also supported.")
        self._run_button = PushButton(text="Run Inference")
        self.label_info = Label(value="(For large images, it may take a while when using CPU. GPU is recommended.)")
        _configure_wrapped_labels(self.label_model, self.label_info)

        self.extend([
            self.model_choice, self.model_path, self.label_model,
            self._image_layer_combo, self.scale,
            self.tile_size, self.device, self._run_button,
            self.label_info
        ])

        self._run_button.clicked.connect(self._run_inference)

    def _build_request(self, img_layer):
        return EMCellFinerRequest(
            model_path=normalize_optional_path(self.model_path.value),
            scale=self.scale.value,
            tile_size=self.tile_size.value,
            device=resolve_emcellfiner_device(self.device.value),
            image=None if img_layer is None else img_layer.data,
        )

    def _run_inference(self):
        img_layer = self._image_layer_combo.value
        if img_layer is None:
            print("No layer selected")
            return

        request = self._build_request(img_layer)
        progress = napari.utils.progress(total=100, desc="EMCellFiner Inference...")

        @thread_worker
        def _worker():
            return run_emcellfiner_single_inference(request)

        worker = _worker()

        @worker.returned.connect
        def _on_result(output_np):
            progress.close()
            upsert_image_layer(self.viewer, output_np, f"{img_layer.name}_EMCFiner_SR")
            print("Inference Finished")

        @worker.errored.connect
        def _on_error(err):
            progress.close()
            print("Inference Error:", err)

        worker.start()

class EMCellFinerBatchInferWidget(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self.viewer = viewer

        MODEL_ZOO = ["EMCellFiner"]

        self.model_path = FileEdit(label="Model (.pth)", mode="r", nullable=True)
        self.input_dir = FileEdit(label="Input Folder", mode="d")
        self.output_dir = FileEdit(label="Save Folder", mode="d")
        self.scale = ComboBox(label="Scale", choices=[1, 2, 4], value=4)
        self.tile_size = ComboBox(label="Tile Size", choices=[256, 384, 512, 640, 1024], value=512)
        self.device = ComboBox(label="Device", choices=["auto", "cpu", "cuda"], value="auto")
        self.resize_before_inference = CheckBox(label="Resize input before inference", value=False)
        self.resize_factor = FloatSpinBox(label="Resize factor", min=0.01, max=100.0, step=0.05, value=0.25)
        self.resize_algorithm = ComboBox(
            label="Resize algorithm",
            choices=["Nearest Neighbor", "Bilinear", "Bicubic", "Lanczos"],
            value="Bilinear",
        )
        self.model_choice = ComboBox(label="Model", choices=MODEL_ZOO, value="EMCellFiner")
        self._run_button = PushButton(text="Run Batch Inference")
        self._stop_button = PushButton(text="Stop Inference")
        self.label_model = Label(value="(If left blank, the model will be automatically downloaded from the cloud. Manual loading is also supported.")
        self.label_info = Label(value="(For large images, it may take a while when using CPU. GPU is recommended.)")
        _configure_wrapped_labels(self.label_model, self.label_info)

        self.extend([
            self.model_choice, self.model_path, self.label_model,
            self.input_dir, self.output_dir,
            self.scale, self.tile_size, self.device,
            self.resize_before_inference, self.resize_factor, self.resize_algorithm,
            self._run_button, self._stop_button, self.label_info
        ])

        self._run_button.clicked.connect(self._run_batch_inference)
        self._stop_button.clicked.connect(self._stop_worker)
        self.resize_before_inference.changed.connect(self._update_resize_controls_state)

        self._worker = None
        self._stop_flag = False
        self._update_resize_controls_state()

    def _update_resize_controls_state(self):
        enabled = self.resize_before_inference.value
        self.resize_factor.visible = enabled
        self.resize_algorithm.visible = enabled

    def _build_request(self):
        return EMCellFinerRequest(
            model_path=normalize_optional_path(self.model_path.value),
            scale=self.scale.value,
            tile_size=self.tile_size.value,
            device=resolve_emcellfiner_device(self.device.value),
            input_dir=normalize_optional_path(self.input_dir.value),
            output_dir=normalize_optional_path(self.output_dir.value),
            resize_before_inference=self.resize_before_inference.value,
            resize_factor=self.resize_factor.value,
            resize_algorithm=self.resize_algorithm.value,
        )

    def _stop_worker(self):
        self._stop_flag = True
        if self._worker is not None:
            self._worker.quit()
            print("Batch inference stopped by user.")

    def _run_batch_inference(self):
        request = self._build_request()

        if not (request.input_dir and os.path.isdir(request.input_dir)):
            print("Invalid Input Folder")
            return

        if not request.output_dir:
            print("Invalid Output Folder")
            return

        img_files = collect_image_files(request.input_dir)
        ensure_directory(request.output_dir)
        if len(img_files) == 0:
            print("No images found in folder")
            return

        self._stop_flag = False
        progress = napari.utils.progress(range(len(img_files)), desc="Batch Inference...")

        @thread_worker
        def _worker():
            yield from iter_emcellfiner_batch_inference(
                request,
                stop_checker=lambda: self._stop_flag,
            )

        self._worker = _worker()
        worker = self._worker

        @worker.yielded.connect
        def _on_each(args):
            path, save_path, out_np, idx = args
            print(f"idx: {idx} : {os.path.basename(path)} Saved to: ", save_path)
            progress.update(idx + 1)

        @worker.errored.connect
        def _on_err(err):
            progress.close()
            print("Error:", err)

        @worker.finished.connect
        def _on_finished():
            progress.close()
            print("Batch Inference Finished")
            self._worker = None
            self._stop_flag = False

        worker.start()


#----------------------------
# labelme2semantci segmentation mask
#----------------------------
class LabelMe2Seg(Container):
    '''
        using labelme to annotate the labels first, and generate json files.
        Here, using this function we can convert those json files to semantic segmentation masks, labels are png files in P(PIL) mode.
    '''
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self.viewer = viewer


        self.json_path = FileEdit(label="Jsons labels folder", mode="d", nullable=False)
        self.output_dir = FileEdit(label="Save mask Folder", mode="d")
        self.label_name_to_value = FileEdit(label="Label Name to Value (txt)", mode="r", nullable=False)
        
        self._run_button = PushButton(text="Run convert")
        self.info = TextEdit(
                        value=(
                            "Convert labelme json files to semantic segmentation masks (png files).\n"
                            "The label.txt should be written in this formats:\n"
                            "labels.txt: \t\n"
                            "\t \t \n"
                            "_background_ : 0\n"
                            "mito : 1\n"
                            "nu : 2 \n"
                        ),
                    )
        
        self.extend([
            self.json_path,
            self.label_name_to_value,
            self.output_dir,
            
            self._run_button,
            
            self.info,
        ])

        # 按钮绑定
        self._run_button.clicked.connect(self._convert_labelme_json_to_mask)


    def _convert_labelme_json_to_mask(self):

        json_folder = self.json_path.value
        out_dir = self.output_dir.value

        # 读取 label_name_to_value
        with open(self.label_name_to_value.value, 'r', encoding="utf-8") as f:
            text = f.read()
            label_name_to_value = self.auto_parse_label_mapping(text)


        print("Label name to value =", label_name_to_value)
        
        if not osp.exists(out_dir):
            os.mkdir(out_dir)


        img_save_path = osp.join(out_dir, "image")
        labels_save_path = osp.join(out_dir, "label")
        vis_save_path = osp.join(out_dir, "vis")

        os.makedirs(img_save_path, exist_ok=True)
        os.makedirs(labels_save_path, exist_ok=True)
        os.makedirs(vis_save_path, exist_ok=True)

            
        # 遍历全部 json
        for json_file in os.listdir(json_folder):
            if not json_file.endswith(".json"):
                continue

            json_path = os.path.join(json_folder, json_file)
            data = json.load(open(json_path))
            imageData = data.get("imageData")

            if not imageData:
                imagePath = os.path.join(json_folder, data["imagePath"])
                with open(imagePath, "rb") as f:
                    imageData = f.read()
                    imageData = base64.b64encode(imageData).decode("utf-8")
            img = utils.img_b64_to_arr(imageData)
            
            
            # 生成mask
            lbl, _ = labelme_utils.shapes_to_label(
                img.shape,
                data['shapes'],
                label_name_to_value
            )
            
            label_names = [None] * (max(label_name_to_value.values()) + 1)
            for name, value in label_name_to_value.items():
                label_names[value] = name
        
            lbl_viz = imgviz.label2rgb(
                lbl, imgviz.asgray(img), label_names=label_names, loc="rb"
            )
        
            
            PILImage.fromarray(img).convert("RGB").save(osp.join(img_save_path, osp.splitext(data['imagePath'])[0]+".tif"))
            utils.lblsave(os.path.join(labels_save_path, osp.splitext(data['imagePath'])[0] + ".png"), lbl)
            PILImage.fromarray(lbl_viz).save(osp.join(vis_save_path, osp.splitext(data['imagePath'])[0]+ "_labelviz" + ".png"))
            
        print(f"All jsons converted to masks! saved to {labels_save_path}")



    def auto_parse_label_mapping(self, text: str):
        """
        自动识别 JSON / Python dict / YAML / key-value / CSV 等格式，返回 dict。
        """

        text = text.strip()

        # 1. 尝试 JSON（最规范）
        try:
            return json.loads(text)
        except Exception:
            pass

        # 2. 尝试 Python 字典格式
        try:
            return ast.literal_eval(text)
        except Exception:
            pass

        # 3. 尝试 YAML 风格：key: value
        try:
            lines = text.splitlines()
            mapping = {}
            for line in lines:
                if ":" not in line:
                    continue
                key, value = line.split(":", 1)
                key = key.strip()
                value = value.strip()
                if value.isdigit():
                    value = int(value)
                mapping[key] = value
            if mapping:
                return mapping
        except Exception:
            pass

        # 4. 尝试 CSV 或 key,value
        try:
            lines = text.splitlines()
            mapping = {}
            for line in lines:
                if "," not in line:
                    continue
                key, value = line.split(",", 1)
                key = key.strip()
                value = value.strip()
                if value.isdigit():
                    value = int(value)
                mapping[key] = value
            if mapping:
                return mapping
        except Exception:
            pass

        raise ValueError("无法解析标签映射文件，请检查文件格式。")
    
class PhenotypeAnalysis(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        super().__init__()
        self.viewer = viewer
        self.results_df = None  # 用于存储分析结果的 DataFrame
        
        # --- 原有 UI 组件 ---
        self._image_layer = create_widget(label="Image", annotation=Image)
        self._label_layer = create_widget(label="Label", annotation=Labels)
        
        # ... (此处省略你原有的 CheckBox 初始化) ...
        self.label = Label(value="Select features to analyze:")
        _configure_wrapped_label(self.label)
        self.Area_box = CheckBox(label="Area",  value=True)
        self.Perimeter_box = CheckBox(label="Perimeter",  value=True)
        self.Elongation_box = CheckBox(label="Elongation",  value=True)
        self.Roundness_box = CheckBox(label="Roundness",  value=True)
        self.Shape_Complexity_box = CheckBox(label="Shape Complexity",  value=True)
        self.Electron_Density_box = CheckBox(label="Electron Density",  value=True)
        # (假设其他 Box 也已定义)

        # --- 新增 UI 组件 ---
        self.start_button = PushButton(text="Run Analysis")
        self.export_button = PushButton(text="Export to CSV")
        self.export_button.enabled = False  # 初始状态禁用导出
        
        # 创建表格组件
        self.result_table = Table(label="Results")
        
        # 信号连接
        self.start_button.clicked.connect(self._run_phenotype_analysis)
        self.export_button.clicked.connect(self._export_csv)
        
        # 将表格的点击事件连接到定位函数
        # magicgui Table 的 native 控件是 QTableWidget
        self.result_table.native.cellClicked.connect(self._on_table_click)

        self.extend([
            self._image_layer, self._label_layer, self.label,
            self.Area_box, self.Perimeter_box, self.Elongation_box,
            self.Roundness_box, self.Shape_Complexity_box, self.Electron_Density_box,
            self.start_button,
            self.result_table,
            self.export_button
        ])

    def _run_phenotype_analysis(self):
            img_layer = self._image_layer.value
            label_layer = self._label_layer.value
            features = {
                "Area": self.Area_box.value,
                "Perimeter": self.Perimeter_box.value,
                "Elongation": self.Elongation_box.value,
                "Roundness": self.Roundness_box.value,
                "Shape Complexity": self.Shape_Complexity_box.value,
                "Electron Density": self.Electron_Density_box.value,

                }
        
            results_df, instance_mask = analyze_phenotypes(img_layer.data, label_layer.data, features)
                    
            instance_layer_name = f"{label_layer.name}_instances"
            inst_layer = upsert_labels_layer(self.viewer, instance_mask, instance_layer_name)
            
            # 将结果存入类属性
            self.results_df = results_df
            # 更新表格显示
            self.result_table.value = results_df
            # 将属性绑定到图层（这一步对很多 Napari 插件互操作很重要）
            inst_layer.features = results_df
            
            # 激活导出按钮
            self.export_button.enabled = True
            
    def _on_table_click(self, row, col):
            """点击表格行，利用预计算好的质心自动定位"""
            if self.results_df is None or row < 0:
                return
                
            # 1. 安全地获取数据
            # 使用 iloc[row] 获取当前点击行的数据字典
            item_data = self.results_df.iloc[row]
            label_id = int(item_data['label'])
            
            # 2. 找到实例图层 (重要：不要找原始的 label_layer)
            instance_layer_name = f"{self._label_layer.value.name}_instances"
            if instance_layer_name not in self.viewer.layers:
                return
            inst_layer = self.viewer.layers[instance_layer_name]
            
            # 3. 更新选中状态
            inst_layer.selected_label = label_id
            
            # 4. 直接利用 analyze_phenotypes 算好的质心定位
            # 注意：regionprops 的 centroid 返回的是 (row, col)，即 (y, x)
            center_y = item_data['centroid-0']
            center_x = item_data['centroid-1']
            
            # 移动相机
            self.viewer.camera.center = (center_y, center_x)
            self.viewer.camera.zoom = 2.0  # 放大以更好地查看
            

    def _export_csv(self):
        """弹出文件对话框并保存 CSV"""
        if self.results_df is None:
            return
            
        filepath, _ = QFileDialog.getSaveFileName(
            None, "Save Analysis Results", "phenotype_results.csv", "CSV Files (*.csv)"
        )
        
        if filepath:
            self.results_df.to_csv(filepath, index=False)
            print(f"Results saved to: {filepath}")
